### ISSUE TITLE
Reach out to the trustees about adding James to the SR facebook page

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/competition-team-minutes#114]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2019-08-20.md#specific

**Comment by antoinepetty** [comment]
Is this still required given that #113 isn't possible?

**Comment by PeterJCLaw** [comment]
Up to you. I think it might be useful to have more than one person able to add things to the page, however as #113 isn't possible this is definitely not urgent.

**Comment by PeterJCLaw** [comment]
(For clarity: if you think we're not likely to do this in the next couple of weeks, let's close this and let it get re-opened when needed, rather than having it linger around. Re-opening is easy and IMO well worth the clarity that for now we'd not be doing this)
