### ISSUE TITLE
Open up the old google groups mailing lists so they’re easier for people to join

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/competition-team-minutes#115]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2019-08-20.md#specific

This is regarding our planned use of https://groups.google.com/forum/#!forum/srobo as a discussion forum for higher latency discussion than Slack affords.

**Comment by PeterJCLaw** [comment]
I've used the "Contact Owner and Manager" mechanism to see if we can find out who the owner is.

**Comment by RealOrangeOne** [comment]
I have now contacted the trustees (along with Rob and Rich) to see about access.

**Comment by RealOrangeOne** [comment]
I've had a response, and now have owner access to the list.

I've modified the permission such that anyone can join the list, and thus post to it. If necessary, we can dial this back to users requiring acceptance before they can join, but let's leave that for now.

![image](https://user-images.githubusercontent.com/6527489/63887117-fd82c900-c9d3-11e9-9f08-7728d99212ec.png)

Now that the list is open for joining, I'm happy to consider this solved. Rob kindly provided a list of people who are owners of the other mailing lists (`srobo-game@` and `srobo-devel@`), so if we choose to also use those, we know who to contact. Said email chain should have been sent to all competition team members for reference.
