### ISSUE TITLE
Draft invitation email to teams

### ISSUE THREAD

**Issue by sedders123** [srobo/competition-team-minutes#117]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020\2019-08-27.md#specific

**Comment by PeterJCLaw** [comment]
@RealOrangeOne is this blocked by #120? Concretely: can we use the signup form we already have, or are we going to need a new approach? If the latter, then I get the feeling this email might need some rather different wording.

**Comment by PeterJCLaw** [comment]
This has been drafted.
