### ISSUE TITLE
Bug: the actions script doesn't normalise paths on Windows

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/competition-team-minutes#122]
Specifically, we end up with links which are like `.../master/SR2020\2019-08-27.md#specific` (note the backslash), which then don't work.

I suspect the fix is likely adding a `.replace(os.path.sep, '/')` somewhere.

**Comment by trickeydan** [comment]
You seem to be using pathlib to build file paths. Where exactly are the backslashes introduced? I feel like your proposed solution might be fixing the symptom rather than the problem.

**Comment by PeterJCLaw** [comment]
The script correctly uses `pathlib` for paths, the issue is that paths aren't the same on Windows and the `str(...)` of the value is being used in a url.
