### ISSUE TITLE
Book rooms in Southampton Uni for Kickstart

### ISSUE THREAD

**Issue by sedders123** [srobo/competition-team-minutes#145]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2019-09-20.md#specific

**Comment by PeterJCLaw** [comment]
Is this a duplicate of https://github.com/srobo/tasks/issues/394?

**Comment by sedders123** [comment]
Yes it looks like it is. Closing in favour of srobo/tasks#394
