### ISSUE TITLE
Organise tech days

### ISSUE THREAD

**Issue by sedders123** [srobo/competition-team-minutes#146]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2019-09-20.md#specific

**Comment by PeterJCLaw** [comment]
This has started. @Adimote put together a spreadsheet of possible dates: https://docs.google.com/spreadsheets/d/1t_ZCXjmxC6tCsvOaaKSW6hEhzYKkiNLp1sT-VENrp5U/edit

Summary is:
> 2019-11-30 (Teaching tech day)
> 2020-01-25
> 2020-02-08
> 2020-03-28
> 2020-04-25 (If competition is later than April)

**Comment by RealOrangeOne** [comment]
I've contacted Diane about the availability of the RPi Foundation.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne any updates on Cambridge?

@JennyLynnFletcher do you think we'd be able to use the Uni to host this again?

**Comment by PeterJCLaw** [comment]
@Adimote there's some odd spacing regarding the second tech day in 2020 in the proposed dates. Was there a reason not to have a tech day on either the 14th or 21st March, rather than it being as late as the 28th?

**Comment by PeterJCLaw** [comment]
Update on the suggested dates:

* ~2019-11-30 (Teaching tech day)~
* 2020-01-25
* 2020-02-29
* 2020-03-28

Competition dates:
* 2020-03-18 (if Reading)
* 2020-04-25 (If Southampton)

**Comment by PeterJCLaw** [comment]
The initial ones are done. There's not a lot of value keeping this open, though we'll likely add some more later in the year.
