### ISSUE TITLE
Send email to unconfirmed teams announcing kickstarts

### ISSUE THREAD

**Issue by sedders123** [srobo/competition-team-minutes#148]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2019-09-20.md#specific

**Comment by sedders123** [comment]
Blocked on #144

**Comment by sedders123** [comment]
#144 has been closed now, this should be unblocked. (Though I'm not sure if we actually have any unconfirmed teams)

**Comment by PeterJCLaw** [comment]
There are no unconfirmed teams; all teams were emailed about Kickstart.
