### ISSUE TITLE
Finalise rules document

### ISSUE THREAD

**Issue by sedders123** [srobo/competition-team-minutes#149]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2019-09-20.md#specific

**Comment by PeterJCLaw** [comment]
Is this different to https://github.com/srobo/tasks/issues/355?

**Comment by sedders123** [comment]
I agree that there doesn't seem to be much distinction, Jake said he was happy to own the finalising of the rules document and gave examples of corralling others to review the document and propose changes. @RealOrangeOne are you happy to be assigned to srobo/tasks#355 and close this?

**Comment by RealOrangeOne** [comment]
That I am!
