### ISSUE TITLE
Get access to srobo-announce google group

### ISSUE THREAD

**Issue by sedders123** [srobo/competition-team-minutes#152]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2019-09-20.md#specific

**Comment by PeterJCLaw** [comment]
https://groups.google.com/forum/#!forum/srobo-announce exists already...?

**Comment by sedders123** [comment]
I get the following message trying to view the group 
![image](https://user-images.githubusercontent.com/1496834/65463988-bf50bc00-de50-11e9-82fb-fbf20bd9d13f.png). Guess we need to sort out permissions

**Comment by RealOrangeOne** [comment]
I too can't see this group. @PeterJCLaw I guess by the sounds of it you already have access to it?

**Comment by PeterJCLaw** [comment]
How does the plan for this group relate to the plan for the srobo-news group mentioned in #151? They seem pretty similar, so it would be useful to understand what the planned differences are (and we should then include those differences in the descriptions of the groups).

**Comment by RealOrangeOne** [comment]
My intention for `srobo-announce` is to replace exactly what we use MailChimp for currently. It'll be used for general PSA, and recruitment. It'll be the main mailing list.

`srobo-news` will be the more frequent newsletter-y mailing list ("SR(A)WN"), for more frequent "I wonder what's going on in SR and where I can help" type updates.

This should **definitely** be reflected in the mailing list, runbook, and #150

**Comment by PeterJCLaw** [comment]
@RealOrangeOne @andybusse @Adimote are now "Owner"s of the group.
