### ISSUE TITLE
Email Trustees asking about use of social media for attracting sponsors

### ISSUE THREAD

**Issue by sedders123** [srobo/competition-team-minutes#153]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2019-09-20.md#specific

**Comment by antoinepetty** [comment]
Have emailed Diane with cc to trustees, will update/close this ticket as needed based on the response.

**Comment by antoinepetty** [comment]
Will delay bumping this for another week as trustees may not have met since the email was sent

**Comment by antoinepetty** [comment]
Update: they are interested. They will send me appropriate wording to put out.
