### ISSUE TITLE
Update Cambridge website post with details of Uni

### ISSUE THREAD

**Issue by sedders123** [srobo/competition-team-minutes#155]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2019-09-27.md#specific

Post can be found in the website [repo](https://github.com/srobo/website/blob/master/_events/sr2020/cambridge-kickstart.md)

**Comment by PeterJCLaw** [comment]
Now that the address is on the website, is there anything left here/

**Comment by PeterJCLaw** [comment]
https://github.com/srobo/website/pull/170 and https://github.com/srobo/website/pull/171 solve this.
