### ISSUE TITLE
Send email to teams on 1st October confirming Cambridge location

### ISSUE THREAD

**Issue by sedders123** [srobo/competition-team-minutes#157]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2019-09-27.md#specific

## Also include:

- Southampton venue details?
- Number of teams?
- A PII-free way of confirming everyone's kickstart locations

**Comment by PeterJCLaw** [comment]
Redundant since https://github.com/srobo/team-emails/pull/29 is going out soon.
