### ISSUE TITLE
Define a process for handing kits out at kickstart

### ISSUE THREAD

**Issue by Adimote** [srobo/competition-team-minutes#160]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2019-10-11.md#specific

**Comment by PeterJCLaw** [comment]
I'm not sure why this needs a task (it never has in the past).

Process:
- Hand out copies of the kit disclaimer form to team leaders, for them to sign
- Team leaders come to your desk with signed copies, which they exchange for a kit
- You note down which kit was given to which team
- We later update the inventory to match what happened

**Comment by RealOrangeOne** [comment]
The above is correct, with a slight modification.

The intention is we send out the kit disclaimer forms in advance, to speed up the issuing process.

The sheet https://docs.google.com/spreadsheets/d/1zkyD5a0_TtmIebk-MBuNNCQ7-AVxSflv4cGvCzA0PC0/edit?usp=sharing contains a list of teams, and entries for the part code of the RUBs, and whether the team has signed a disclaimer form.
