### ISSUE TITLE
Find a courier to ship the team kits

### ISSUE THREAD

**Issue by Adimote** [srobo/competition-team-minutes#165]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2019-10-18.md#specific

**Comment by RealOrangeOne** [comment]
Closely related to https://github.com/srobo/tasks/issues/343 and https://github.com/srobo/tasks/issues/352.

**Comment by PeterJCLaw** [comment]
Closing in favour of the existing tasks.
