### ISSUE TITLE
Reach out to Diane about Cambridge tech days

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/competition-team-minutes#170]
The Raspberry Pi Foundation have some rooms which would work great for a tech day! We should contact Diane about booking those areas, given some potential tech day dates.

Related to #146

**Comment by RealOrangeOne** [comment]
Have sent a message

**Comment by RealOrangeOne** [comment]
DIane's been on holiday last week, so hasn't had a chance to inquire. I'll report back next week!

**Comment by PeterJCLaw** [comment]
Hopefully we'll cover this when hand over the remaining kits for dispatch to teams.

**Comment by PeterJCLaw** [comment]
@JennyLynnFletcher any update on either this or hosting a Tech Day elsewhere in Cambridge?
