### ISSUE TITLE
Follow up on the Reading society contact

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/competition-team-minutes#183]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2019-11-27.md#specific

**Comment by RealOrangeOne** [comment]
This has been left over to our Reading contact to chase. Apparently the society has dropped off the map a little on their end too!

**Comment by RealOrangeOne** [comment]
Apparently, the society has folded, which is annoying. 

I'm hoping through RUSU we can still do some outreach there to get some potential new volunteers, but I think that's out of scope of this ticket.
