### ISSUE TITLE
Get digital plans for the Reading Venue

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/competition-team-minutes#196]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2020-01-08.md#specific

**Comment by RealOrangeOne** [comment]
I've sent this email now.

I'll close it once we have the plans.

**Comment by RealOrangeOne** [comment]
I have the plans!

https://drive.google.com/a/studentrobotics.org/file/d/0B9GxsNF1GEftT0NkWS1JZ0haM0JaNEVpZTFlUTJOZURyaFcw/view?usp=sharing

(SR account required as unsure if public documents)

**Comment by Tyler-Ward** [comment]
You will probably need more detailed plans than this e.g. dimensions, locations of non 13A power, fire routes, ect

**Comment by RealOrangeOne** [comment]
We got most of the dimensions whilst we were there, and noted down a couple of locations of 13A's and fire exits. 

Any final details should be resolved during #195
