### ISSUE TITLE
Contact Tom W regarding booking some Southampton Tech Days

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/competition-team-minutes#197]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2020-01-08.md#specific

**Comment by antoinepetty** [comment]
Have contacted and booked for the 8th Feb. Tom is unable to attend. Need another person with Southampton uni access

**Comment by PeterJCLaw** [comment]
@antoinepetty do you know which rooms have been booked?

**Comment by antoinepetty** [comment]
25 / 1009
