### ISSUE TITLE
Ask the Kit Team for a call to discuss plans for assigning volunteers for helpdesk and kit retrieval

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/competition-team-minutes#199]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2020-01-08.md#specific

**Comment by RealOrangeOne** [comment]
Have sent as an email, as things like this generally get lost in Slack.

**Comment by PeterJCLaw** [comment]
Having now imported tasks, there are some others which are very much related to team-kits (https://github.com/srobo/tasks/issues?q=is%3Aopen+is%3Aissue+label%3A%22A%3A+Team+Kits%22+milestone%3A%22SR2020+Competition%22). It would be great if the  Kit team could take those tasks too.

**Comment by RealOrangeOne** [comment]
I've sent a follow up email asking for comments on the tasks repo too.

**Comment by RealOrangeOne** [comment]
I had a chat with @TomWheal this evening, the outcome was:
- Those assigned to helpdesk should have a working knowledge of the kit, and how to use it.
- "Team Kits" label is fine for separating issues, but as always, if someone sees an issue and can help, they can / should. It's not the competition team's task list!
- Those assigned to helpdesk should not be the ones handing out batteries, there should be a (perhaps physical) divide
- Tom, if available, will take the "Head Helpdesk" role. Remaining committee / team members should be scheduled as usual, however a skew towards kit-related roles is probably ideal.

**Comment by PeterJCLaw** [comment]
Thanks, that mostly sounds good.

> * Those assigned to helpdesk should not be the ones handing out batteries, there should be a (perhaps physical) divide

I'm surprised and a little concerned about this. What's the rationale for this?

It strikes me that this is going to mean that a lot of requests for batteries will get the response "I can't help with that, go over there (_pointing along the desk_)" as well as mean that two volunteers are now needed to permanently sit at Helpdesk where previously only a single one was needed. Moreover the person sat handing out batteries will have very little to do but be unable to actually help teams.

Previously we have had a pot of batteries at Helpdesk and allowed any volunteer there to hand them out. I'm not aware that there have ever been issues with this.

**Comment by TomWheal** [comment]
> I'm surprised and a little concerned about this. What's the rationale for this?

There were times last year where there was such a big queue for batteries it was causing a firerisk, becasue all the volenteers were busy handling technical problems with teams. Moving the technical help of the help desk will help with this as well, so its likley batteries will still be available on the help desk. 

This probably isnt the issue to discuss this in, as it is more relevent to how the help desk is run.

**Comment by PeterJCLaw** [comment]
> This probably isnt the issue to discuss this in, as it is more relevent to how the help desk is run.

:+1: --> https://github.com/srobo/tasks/issues/524
