### ISSUE TITLE
Ask the Kit Team for an update on kit shipping to the team in Guernsey

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/competition-team-minutes#202]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2020/2020-02-05.md#specific

**Comment by RealOrangeOne** [comment]
According to @trickeydan yesterday, it's intending to be dispatched in the next few days.

**Comment by RealOrangeOne** [comment]
Kit will hopefully be dispatched early next week.
