### ISSUE TITLE
Contact Reading RE remaining questions

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/competition-team-minutes#204]
- What locations can be used for a volunteer quiet area?
- How many radios can we hire, and how many different frequencies can we used (ideally 3) (https://github.com/srobo/tasks/issues/422)
- Can we use confetti canons?
- Can we use carpet tape on the floor of Mojo's, and _tape_ (likely electrical) on the floor in the other rooms?
- How do the rooms need to be left once we leave? Everything emptied or leaving hired tables/chairs in-place?
- How will WiFi work? What information do they need? (https://github.com/srobo/tasks/issues/526)
- How much additional power distro will we need (at additional cost?). (https://github.com/srobo/tasks/issues/515, https://github.com/srobo/tasks/issues/428, https://github.com/srobo/tasks/issues/417)
- Will you be around Thursday / Sunday to help with setup / teardown queries?
- Confirming starbucks / sandwich chillers will be open / populated

**Comment by PeterJCLaw** [comment]
> * Confirming starbucks / sandwich chillers will be open / populated

Maybe also ask about the other shops which were up the stairs? Not sure whether we want those, but there was more food places up there which might be worth seeing if they'll open.

Separately:
 * If we're hiring in external lights (likely we are), would they be able to do the work to attach them to their truss?
 * Will they be able to help us put out signage from the road to the car park?

**Comment by WillB97** [comment]
Worth checking if we can run a few cables over the ceiling tiles (particularly between staging and livestream)
And also finding out what their opinion is on us using their ladders

**Comment by WillB97** [comment]
Can we get a copy of their current chamsys show file to help with lighting setup?

**Comment by RealOrangeOne** [comment]
My intention is to write this tomorrow, ready to send Thursday morning, so that's the cut-off.

**Comment by WillB97** [comment]
Have we confirmed whether they are laying out the power or we are?

**Comment by RealOrangeOne** [comment]
- Quiet Area: RUSU Boardroom booked for Saturday and Sunday
- Radios: In progress. Handsets are at least 12 channel, though
- Green light to confetti :tada:
- Ok on carpet tape ("You would be hard pushed to damage the floor more than it already has been!!")
- Ok on tape to bound team pits ("masking tape is probably the best to use")
- Sounds like they're ok with the rooms being left however, so long as it's reasonable:

> Q: How would you want the rooms left after the event, and what state will they be in Thursday morning? This helps us plan and account for time when setting up / tearing down our kit. Are you going to handle moving the existing furniture in / out of the rooms, or is that something we'd need to do? We're of course happy to assist! 

> A: We have staff to ensure the rooms and furniture are in the right place at the right time

- Starbucks will be open on the Friday and Saturday. Just confirming times for Sunday.
- On the Friday, there may be some students around, but doesn't really matter.
- RUSU can assist with putting things on the truss

>  We will be hiring electrical contractor to ensure you have sufficient power sockets, so we will utilise them to sort the truss attachments also.  We have ladders and we just need to ensure we give you a ‘basic training’ to satisfy our H&S

- We have probably closen the worst place for livestream in the whole building. 

> Somewhere nearer the Mojos bar would be better, maybe at the Mojos entrance?

Will update relevant issues shortly.
