### ISSUE TITLE
Rename "Competition Team Meetings"

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/competition-team-minutes#230]
The "Competition Team Meetings" for the last year (competition SR2020) have always been open to any and all volunteers to attend and contribute to. Unfortunately, this never happened.

By changing the name of the meeting, it will hopefully encourage the wider ("satellite") volunteers to attend and thus contribute more. 

This aids the "open by default" value.

The competition team will still need an avenue to discuss sensitive topics, although these can be organised and planned on an ad-hoc basis (likely via email).

This change is suggested for the SR2021 competition year.

**Comment by PeterJCLaw** [comment]
The challenge I see here is that "Competition" is already an overloaded term. Would it still be clear that such meetings might discuss mentoring, kickstart, tech days, general organisation, etc.?

**Comment by RealOrangeOne** [comment]
We did this.

Whilst it's not obvious whether it's directly related to the title of the meetings, they are better attended
