### ISSUE TITLE
Look into localisation

### ISSUE THREAD

**Issue by sedders123** [srobo/competition-team-minutes#242]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2021/2020-11-12.md#specific

**Comment by PeterJCLaw** [comment]
This happened. For SR2021 we're using a collection of [Emitters](https://www.cyberbotics.com/doc/reference/emitter) and [Receivers](https://www.cyberbotics.com/doc/reference/receiver) to achieve localisation without vision.
