### ISSUE TITLE
Prepare presentation for module 2 announcement

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/competition-team-minutes#254]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2021/2021-01-14.md#specific

**Comment by RealOrangeOne** [comment]
I've created a basic presentation at https://docs.google.com/presentation/d/1Nr-doA9SAr0jg47AlyuTW3exFSvjkQY1lY-vTLLqc54/edit?usp=sharing, which i'll update soon with final visuals
