### ISSUE TITLE
Sort Will an @sr account (and/or poke a Trustee)

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/competition-team-minutes#257]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2021/2021-01-14.md#specific

**Comment by RealOrangeOne** [comment]
I've emailed DIane about this.

**Comment by PeterJCLaw** [comment]
@WillB97 did this get sorted? If not, we should ping Diane again.

**Comment by WillB97** [comment]
I haven't received anything. If an email was sent then we could try a different email address.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne can you repeat your poking?

**Comment by PeterJCLaw** [comment]
Perhaps @Scarzy  or @dmasseySR could help here?
