### ISSUE TITLE
Email volunteers with an update and inviting them to get involved

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/competition-team-minutes#277]
From https://github.com/srobo/competition-team-minutes/blob/master/SR2021/2021-02-11.md#specific

The email would contain:
- Doings dates

We should check in with the kit team before sending.

**Comment by WillB97** [comment]
Is this a duplicate of #285?

**Comment by RealOrangeOne** [comment]
Yes and no. This was aimed at a more general "get involved" email, whereas I think #285  was simply notification of a doing. 

Either way neither of the emails have been sent.

We should probably close this in favour of #285, and make sure that email is also a generic "get involved" email.

**Comment by PeterJCLaw** [comment]
This was carried forwards into #285.
