### ISSUE TITLE
Retrieve storage keys that do not belong to Trustee or core team members

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/competition-team-minutes#8]
From https://github.com/srobo/core-team-minutes/blob/master/2018/2018-07-24.md#general

**Comment by andybusse** [comment]
Rich just emailed with the details, key will be forwarded to whoever we like - "who are the keyholders" is on tomorrow's agenda.

**Comment by PeterJCLaw** [comment]
@andybusse do we know who else has keys that we need to retrieve? (No need to put names on this ticket - I'm just trying to work out whether this is just a case of contacting people, or if we first need to work out who has the keys)

**Comment by PeterJCLaw** [comment]
This is no longer a useful task.
