### ISSUE TITLE
Publicise the start of planning for SR2020

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/competition-team-minutes#99]
As discussed in https://github.com/srobo/competition-team-minutes/pull/98, sort of.

We will soon need to publicise the start of SR2020. For this, we'll need volunteers! We need to define where activities and discussions will happen (and in what form), and how people can get involved, however actively they wish.

- Post to social media about helping out
- Post to srobo@googlegroups.com
- Post to the mailchimp announcement list

The exact copy of the announcement will end up in https://github.com/srobo/volunteer-emails/.

## Contents:

- Submitting game suggestions
- Meetings
- How the mailing lists will be used
- Getting people you know involved
- HIgh-level timelines (maybe?)
- What _is_ the competition team?

**Comment by PeterJCLaw** [comment]
I think this is done? I saw there are some posts on social media, is there anything outstanding here?

**Comment by RealOrangeOne** [comment]
## Contents:

- [x] Submitting game suggestions
- [x] Meetings
- [x] How the mailing lists will be used (mostly)
- [x] Getting people you know involved
- [ ] HIgh-level timelines (maybe?)
- [x] What is the competition team?

Looks like all that's outstanding is having advertised the high-level timeline of the competition cycle, which is fairly close to what we normally do, so I think that's fine

**Comment by antoinepetty** [comment]
Sorry I've been a bit out of the loop. Have we resolved the issues with Google Groups? I don't remember sending anything to srobo@googlegroups.com although perhaps this was because the issue was written before we knew of problems.

**Comment by PeterJCLaw** [comment]
We'll publicise the mailing list separately.
